### ISSUE TITLE
SDL_INIT_AUDIO causes no video to display

### ISSUE THREAD

**Issue by erfg12** [ps2dev/ps2sdk-ports#120]
Here's my code:
```
#include <SDL/SDL.h>
#include <SDL/SDL_endian.h>
#include <SDL/SDL_ttf.h>
#include <SDL/SDL_mixer.h>

int SCREEN_WIDTH = 640;
int SCREEN_HEIGHT = 480;

SDL_Surface* screen = NULL;
int quit = 0;

void game_loop() {
	SDL_Event e;

	SDL_FillRect(screen, NULL, SDL_MapRGB(screen->format, 0, 0, 255));

	while (SDL_PollEvent(&e)) {
		if (e.type == SDL_QUIT)
			quit = 1;
	}

	SDL_Flip(screen);
}

int main(int argc, char* args[])
{
	if (SDL_Init(SDL_INIT_VIDEO|SDL_INIT_AUDIO) != 0) // Initialize SDL
	{
		printf("SDL could not initialize! SDL_Error: %s\n", SDL_GetError());
	}
	else
	{
		screen = SDL_SetVideoMode(SCREEN_WIDTH, SCREEN_HEIGHT, 16, 0);
	
		while (quit == 0) {
			game_loop();
		}
	}

	SDL_Quit();

	return 0;
}
```
With this, I get a black screen. If I remove the SDL_INIT_AUDIO I get a blue screen like the code shows.

**Comment by thp** [comment]
Have you tried calling these 3 functions before calling `SDL_Init()`?

```
    SifLoadFileInit();
    SifInitIopHeap();
    sbv_patch_enable_lmb();
```

These (or a subset of them) headers are needed:

```
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <iopheap.h>
#include <sbv_patches.h>
```

In your linker flags, you might need to link against `libpatches.a`:

```
-L$(PS2SDK)/ee/lib -lpatches
```

SDL seems to use an embedded version of `audsrv.irx` that is loaded by `SifExecModuleBuffer()` and that function only seems to work once these functions are called.

**Comment by fjtrujy** [comment]
This is because you aren’t linking proper libraries.
Take this one as example to follow:
https://github.com/sergiou87/open-supaplex/blob/master/ps2/Makefile

**Comment by erfg12** [comment]
Oh, I forgot `-lSDL2main`, thank you.

**Comment by erfg12** [comment]
Ok my game is running, however when I go to do:
`Mix_LoadMUS("cdrom0:\music.wav");` the game locks up.

**Comment by fjtrujy** [comment]
Loading from cdrom… I’m not sure if it will work. You can load resources using relative path.
Try with PCSX2 and be sure that host filesystem is enabled

**Comment by fjtrujy** [comment]
Closing this issue, please ping me here if you still have issues
