### ISSUE TITLE
fail build (aalib, madplay)

### ISSUE THREAD

**Issue by sl1pkn07** [ps2dev/ps2sdk-ports#2]
Hi

fail build SDL PS2 port
http://sl1pkn07.no-ip.com/paste/view/ac4b8bd9

greetings

EDIT: fixed
EDIT2: all includes has a executable bit. is normal?
http://sl1pkn07.no-ip.com/paste/view/a39e71f3

other includes, from ode, libjpeg also have that bit

**Comment by sp193** [comment]
Regarding aalib: I don't know if we can support it, as it is now. It appears to expect a sockets layer like the one in Linux, but the PS2SDK does not natively have such a thing.

We have LWIP, which supplies a sockets layer, but I don't think that is linked to stdio... so opening a socket with a FD of 0 may not work as it does on Linux.

**Comment by AKuHAK** [comment]
After #24 this can be closed as of now aalib and madplay are compilable libraries.
