### ISSUE TITLE
User Side Issue 'make[1]: execvp: Permission denied'

### ISSUE THREAD

**Issue by PGAnonamous** [ps2dev/ps2sdk-ports#25]
I know that this is an issue on my side however I cannot seem to figure out exactly what is causing it or if it even effects anything. I receive this every time I make and install the freetype port.

`make[1]: execvp: ./include/freetype/freetype.h: Permission denied`

If someone could tell me how to solve this or assure that it is safe to ignore it would be appreciated.

**Comment by AKuHAK** [comment]
It is not issue - its just warning which appeared after update to latest freetype2. BTW very strange warning anyway not related to ps2sdk-ports.

**Comment by PGAnonamous** [comment]
It hasn't caused me any problems I just thought maybe I was missing something and couldn't seem to find any relavent information from Google. I can still build anything using freetype, such as OPL, without an issue.

Thank you,
Anonamous
