### ISSUE TITLE
Make fails on Debian 9

### ISSUE THREAD

**Issue by BatRastard** [ps2dev/ps2sdk-ports#31]
Toolchain and PS2SDK compiled fine but the following happen with ps2sdk-ports ... 

```
> bat@debian:~/ps2sdk-ports$ make
> git submodule init && git submodule update
> Submodule 'freetype2/src' (https://git.savannah.gnu.org/git/freetype/freetype2) registered for path 'freetype2/src'
> Submodule 'libpng/src' (https://github.com/glennrp/libpng) registered for path 'libpng/src'
> Submodule 'libtap' (git://github.com/mlafeldt/libtap.git) registered for path 'libtap'
> Submodule 'zlib/src' (https://github.com/madler/zlib) registered for path 'zlib/src'
> Cloning into '/home/bat/ps2sdk-ports/freetype2/src'...
> Cloning into '/home/bat/ps2sdk-ports/libpng/src'...
> Cloning into '/home/bat/ps2sdk-ports/libtap'...
> Cloning into '/home/bat/ps2sdk-ports/zlib/src'...
> Submodule path 'freetype2/src': checked out '86bc8a95056c97a810986434a3f268cbe67f2902'
> Submodule path 'libpng/src': checked out '5944b9473083c5d03c4600ac5d1675394598e41c'
> Submodule path 'libtap': checked out 'c970b61829973fe2fb00c6a44ee399373baeab49'
> Submodule path 'zlib/src': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
> make -C aalib
> make[1]: Entering directory '/home/bat/ps2sdk-ports/aalib'
> make -C src all
> make[2]: Entering directory '/home/bat/ps2sdk-ports/aalib/src'
> Makefile:66: /Defs.make: No such file or directory
> /bin/sh: 0: Illegal option --
> /bin/sh: 0: Illegal option -p
> /bin/sh: 0: Illegal option -p
> /bin/sh: 0: Illegal option -p
> /bin/sh: 0: Illegal option -p
> make[2]: *** No rule to make target '/Defs.make'.  Stop.
> make[2]: Leaving directory '/home/bat/ps2sdk-ports/aalib/src'
> Makefile:7: recipe for target 'all' failed
> make[1]: *** [all] Error 2
> make[1]: Leaving directory '/home/bat/ps2sdk-ports/aalib'
> Makefile:10: recipe for target 'aalib' failed
> make: *** [aalib] Error 2
```

**Comment by AKuHAK** [comment]
$PS2SDK is not set

чт, 3 янв. 2019 г., 23:09 BatRastard <notifications@github.com>:

**Comment by BatRastard** [comment]
Profile wasn't sourced, hence why $PS2DEV was missing. Once that was set, make still fails at the "make --C src install" phase while building aalib because - for some reason - it doesn't have the permissions to create the folders in /usr/local/ps2dev/ps2sdk/ports/ ... 

``

**Comment by sp193** [comment]
Have you tried to use the power of sudo:
```
sudo make install
```

**Comment by BatRastard** [comment]
Yeah, and that gives me an error regarding ee-cc. It's weird - I pass on the last few Debian based distros (i.e Mint & Ubuntu) and next thing I know, they nailed everything down to the point where adding the $PATH variables to .bashrc tore everything up to where even a "sudo" or an "ls - l" wouldn't work ... ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sp193** [comment]
FYI: https://unix.stackexchange.com/questions/460478/debian-su-and-su-path-differences/460769#460769

**Comment by sp193** [comment]
So what I am doing now to make things easier, is to create a "ps2dev" group, make myself part of it, change the ownership of ``/usr/local/ps2dev`` to the ps2dev group and to give read & write access to the ps2dev group. Anyway, perhaps we should have always been doing things this way, as using the superuser is a security risk.

With the necessarily privileges (either as root or you sudo everything):
```
groupadd ps2dev
usermod -a -G ps2dev yourusername
chown yourusername:ps2dev -R /usr/local/ps2dev
chmod g+wr -R /usr/local/ps2dev
```

**Comment by BatRastard** [comment]
I almost changed ownership of /usr/local/ps2dev to myself but demurred because I'm used to the local copy under $HOME as having user permissions while /usr/local/ps2dev falls under root. Thanks for the link though - that sure makes it clear as to how I ended up botching the paths of both root and $HOME in Linux Mint to the point that no terminal commands worked and neither did my password after editing .profile and bashrc ... Infinite loops at the login screen are NOT fun ... 

Anyway, your post got me further down the line but unfortunately not far enough. Quite a bit of errors and warnings (such as "visibility" attribute spam from 'ps2dsk-ports/lua) but the worst came from SDL where I think the problem is due to not having gsKit installed yet ... 

`make[2]: Entering directory '/home/bat/ps2sdk-ports/sdl/src'
rm -f ../lib/libsdl.a ../lib/libsdlmain.a SDL.o SDL_error.o SDL_fatal.o SDL_getenv.o SDL_loadso.o video/SDL_video.o video/SDL_surface.o video/SDL_pixels.o video/SDL_blit.o video/SDL_blit_0.o video/SDL_blit_1.o video/SDL_blit_N.o video/SDL_blit_A.o  video/SDL_RLEaccel.o video/SDL_cursor.o video/SDL_bmp.o video/SDL_yuv.o video/SDL_yuv_sw.o video/SDL_stretch.o thread/SDL_thread.o  events/SDL_events.o events/SDL_quit.o events/SDL_active.o events/SDL_keyboard.o events/SDL_mouse.o events/SDL_resize.o thread/generic/SDL_syscond.o thread/generic/SDL_sysmutex.o audio/SDL_wave.o audio/SDL_audio.o audio/SDL_audiomem.o audio/SDL_audiocvt.o audio/SDL_mixer.o file/SDL_rwops.o cdrom/SDL_cdrom.o  timer/SDL_timer.o  joystick/SDL_joystick.o  endian/SDL_endian.o main/ps2sdk/sdl_main.o thread/ps2sdk/SDL_syssem.o thread/ps2sdk/SDL_systhread.o timer/ps2sdk/SDL_systimer.o video/ps2sdk/SDL_ps2video.o audio/ps2sdk/SDL_ps2audio.o  cdrom/ps2sdk/SDL_syscdrom.o joystick/ps2sdk/ps2joystick.o audio/ps2sdk/audsrv_irx.o  audio/ps2sdk/freesd_irx.o joystick/ps2sdk/sio2man_irx.o joystick/ps2sdk/padman_irx.o joystick/ps2sdk/mtapman_irx.o main/arch.o main/ps2sdk/sdl_main.o audio/ps2sdk/freesd_irx.c joystick/ps2sdk/sio2man_irx.c joystick/ps2sdk/padman_irx.c joystick/ps2sdk/mtapman_irx.c audio/ps2sdk/audsrv_irx.c video/ps2sdk/ps2kbd_irx.c video/ps2sdk/ps2mouse_irx.c video/ps2sdk/ps2usbd_irx.c
make[2]: Leaving directory '/home/bat/ps2sdk-ports/sdl/src'
make -C test clean
make[2]: Entering directory '/home/bat/ps2sdk-ports/sdl/test'
rm -f testtimer.elf testcdrom.elf testendian.elf testerror.elf testjoystick.elf testver.elf checkkeys.elf testtimer.o testcdrom.o testendian.o testerror.o testjoystick.o testver.o checkkeys.o
make[2]: Leaving directory '/home/bat/ps2sdk-ports/sdl/test'
rm -f -r lib
make[1]: Leaving directory '/home/bat/ps2sdk-ports/sdl'
make -C sdlimage
make[1]: Entering directory '/home/bat/ps2sdk-ports/sdlimage'
ee-gcc -D_EE -O2 -G0 -Wall -DLOAD_BMP -DLOAD_GIF -DLOAD_JPG -DLOAD_LBM -DLOAD_PCX -DLOAD_PNG -DLOAD_PNM -DLOAD_TGA -DLOAD_XCF -DLOAD_XPM -DLOAD_TIF -I/usr/local/ps2dev/ps2sdk/ee/include -I/usr/local/ps2dev/ps2sdk/common/include -I. -I./include -I/usr/local/ps2dev/ps2sdk/ports/include -I/usr/local/ps2dev/ps2sdk/ports/include/zlib -I/usr/local/ps2dev/ps2sdk/ports/include/SDL -c IMG.c -o IMG.o
In file included from IMG.c:31:
include/SDL_image.h:30:17: SDL.h: No such file or directory
include/SDL_image.h:31:25: SDL_version.h: No such file or directory
include/SDL_image.h:32:24: begin_code.h: No such file or directory
In file included from IMG.c:31:
include/SDL_image.h:59: syntax error before "const"
include/SDL_image.h:59: warning: type defaults to `int' in declaration of `IMG_Linked_Version'
include/SDL_image.h:59: warning: data definition has no type or storage class
include/SDL_image.h:69: syntax error before "SDL_Surface"
include/SDL_image.h:69: syntax error before '*' token
include/SDL_image.h:69: warning: type defaults to `int' in declaration of `IMG_LoadTyped_RW'
include/SDL_image.h:69: warning: data definition has no type or storage class
include/SDL_image.h:71: syntax error before "SDL_Surface"
include/SDL_image.h:71: warning: type defaults to `int' in declaration of `IMG_Load'
include/SDL_image.h:71: warning: data definition has no type or storage class
include/SDL_image.h:72: syntax error before "SDL_Surface"
include/SDL_image.h:72: syntax error before '*' token
include/SDL_image.h:72: warning: type defaults to `int' in declaration of `IMG_Load_RW'
include/SDL_image.h:72: warning: data definition has no type or storage class
include/SDL_image.h:77: syntax error before "int"
include/SDL_image.h:77: warning: type defaults to `int' in declaration of `IMG_InvertAlpha'
include/SDL_image.h:77: warning: data definition has no type or storage class
include/SDL_image.h:80: syntax error before "int"
include/SDL_image.h:80: syntax error before '*' token
include/SDL_image.h:80: warning: type defaults to `int' in declaration of `IMG_isBMP'
include/SDL_image.h:80: warning: data definition has no type or storage class
include/SDL_image.h:81: syntax error before "int"
include/SDL_image.h:81: syntax error before '*' token
include/SDL_image.h:81: warning: type defaults to `int' in declaration of `IMG_isPNM'
include/SDL_image.h:81: warning: data definition has no type or storage class
include/SDL_image.h:82: syntax error before "int"
include/SDL_image.h:82: syntax error before '*' token
include/SDL_image.h:82: warning: type defaults to `int' in declaration of `IMG_isXPM'
include/SDL_image.h:82: warning: data definition has no type or storage class
include/SDL_image.h:83: syntax error before "int"
include/SDL_image.h:83: syntax error before '*' token
include/SDL_image.h:83: warning: type defaults to `int' in declaration of `IMG_isXCF'
include/SDL_image.h:83: warning: data definition has no type or storage class
include/SDL_image.h:84: syntax error before "int"
include/SDL_image.h:84: syntax error before '*' token
include/SDL_image.h:84: warning: type defaults to `int' in declaration of `IMG_isPCX'
include/SDL_image.h:84: warning: data definition has no type or storage class
include/SDL_image.h:85: syntax error before "int"
include/SDL_image.h:85: syntax error before '*' token
include/SDL_image.h:85: warning: type defaults to `int' in declaration of `IMG_isGIF'
include/SDL_image.h:85: warning: data definition has no type or storage class
include/SDL_image.h:86: syntax error before "int"
include/SDL_image.h:86: syntax error before '*' token
include/SDL_image.h:86: warning: type defaults to `int' in declaration of `IMG_isJPG'
include/SDL_image.h:86: warning: data definition has no type or storage class
include/SDL_image.h:87: syntax error before "int"
include/SDL_image.h:87: syntax error before '*' token
include/SDL_image.h:87: warning: type defaults to `int' in declaration of `IMG_isTIF'
include/SDL_image.h:87: warning: data definition has no type or storage class
include/SDL_image.h:88: syntax error before "int"
include/SDL_image.h:88: syntax error before '*' token
include/SDL_image.h:88: warning: type defaults to `int' in declaration of `IMG_isPNG'
include/SDL_image.h:88: warning: data definition has no type or storage class
include/SDL_image.h:89: syntax error before "int"
include/SDL_image.h:89: syntax error before '*' token
include/SDL_image.h:89: warning: type defaults to `int' in declaration of `IMG_isLBM'
include/SDL_image.h:89: warning: data definition has no type or storage class
include/SDL_image.h:92: syntax error before "SDL_Surface"
include/SDL_image.h:92: syntax error before '*' token
include/SDL_image.h:92: warning: type defaults to `int' in declaration of `IMG_LoadBMP_RW'
include/SDL_image.h:92: warning: data definition has no type or storage class
include/SDL_image.h:93: syntax error before "SDL_Surface"
include/SDL_image.h:93: syntax error before '*' token
include/SDL_image.h:93: warning: type defaults to `int' in declaration of `IMG_LoadPNM_RW'
include/SDL_image.h:93: warning: data definition has no type or storage class
include/SDL_image.h:94: syntax error before "SDL_Surface"
include/SDL_image.h:94: syntax error before '*' token
include/SDL_image.h:94: warning: type defaults to `int' in declaration of `IMG_LoadXPM_RW'
include/SDL_image.h:94: warning: data definition has no type or storage class
include/SDL_image.h:95: syntax error before "SDL_Surface"
include/SDL_image.h:95: syntax error before '*' token
include/SDL_image.h:95: warning: type defaults to `int' in declaration of `IMG_LoadXCF_RW'
include/SDL_image.h:95: warning: data definition has no type or storage class
include/SDL_image.h:96: syntax error before "SDL_Surface"
include/SDL_image.h:96: syntax error before '*' token
include/SDL_image.h:96: warning: type defaults to `int' in declaration of `IMG_LoadPCX_RW'
include/SDL_image.h:96: warning: data definition has no type or storage class
include/SDL_image.h:97: syntax error before "SDL_Surface"
include/SDL_image.h:97: syntax error before '*' token
include/SDL_image.h:97: warning: type defaults to `int' in declaration of `IMG_LoadGIF_RW'
include/SDL_image.h:97: warning: data definition has no type or storage class
include/SDL_image.h:98: syntax error before "SDL_Surface"
include/SDL_image.h:98: syntax error before '*' token
include/SDL_image.h:98: warning: type defaults to `int' in declaration of `IMG_LoadJPG_RW'
include/SDL_image.h:98: warning: data definition has no type or storage class
include/SDL_image.h:99: syntax error before "SDL_Surface"
include/SDL_image.h:99: syntax error before '*' token
include/SDL_image.h:99: warning: type defaults to `int' in declaration of `IMG_LoadTIF_RW'
include/SDL_image.h:99: warning: data definition has no type or storage class
include/SDL_image.h:100: syntax error before "SDL_Surface"
include/SDL_image.h:100: syntax error before '*' token
include/SDL_image.h:100: warning: type defaults to `int' in declaration of `IMG_LoadPNG_RW'
include/SDL_image.h:100: warning: data definition has no type or storage class
include/SDL_image.h:101: syntax error before "SDL_Surface"
include/SDL_image.h:101: syntax error before '*' token
include/SDL_image.h:101: warning: type defaults to `int' in declaration of `IMG_LoadTGA_RW'
include/SDL_image.h:101: warning: data definition has no type or storage class
include/SDL_image.h:102: syntax error before "SDL_Surface"
include/SDL_image.h:102: syntax error before '*' token
include/SDL_image.h:102: warning: type defaults to `int' in declaration of `IMG_LoadLBM_RW'
include/SDL_image.h:102: warning: data definition has no type or storage class
include/SDL_image.h:104: syntax error before "SDL_Surface"
include/SDL_image.h:104: warning: type defaults to `int' in declaration of `IMG_ReadXPMFromArray'
include/SDL_image.h:104: warning: data definition has no type or storage class
include/SDL_image.h:114:24: close_code.h: No such file or directory
IMG.c:38: syntax error before '*' token
IMG.c:39: warning: no semicolon at end of struct or union
IMG.c:40: warning: type defaults to `int' in declaration of `supported'
IMG.c:42: warning: braces around scalar initializer
IMG.c:42: warning: (near initialization for `supported[0]')
IMG.c:42: warning: initialization makes integer from pointer without a cast
IMG.c:42: warning: excess elements in scalar initializer
IMG.c:42: warning: (near initialization for `supported[0]')
IMG.c:42: warning: excess elements in scalar initializer
IMG.c:42: warning: (near initialization for `supported[0]')
IMG.c:43: warning: braces around scalar initializer
IMG.c:43: warning: (near initialization for `supported[1]')
IMG.c:43: warning: initialization makes integer from pointer without a cast
IMG.c:43: warning: excess elements in scalar initializer
IMG.c:43: warning: (near initialization for `supported[1]')
IMG.c:43: warning: excess elements in scalar initializer
IMG.c:43: warning: (near initialization for `supported[1]')
IMG.c:44: warning: braces around scalar initializer
IMG.c:44: warning: (near initialization for `supported[2]')
IMG.c:44: warning: initialization makes integer from pointer without a cast
IMG.c:44: warning: excess elements in scalar initializer
IMG.c:44: warning: (near initialization for `supported[2]')
IMG.c:44: warning: excess elements in scalar initializer
IMG.c:44: warning: (near initialization for `supported[2]')
IMG.c:45: warning: braces around scalar initializer
IMG.c:45: warning: (near initialization for `supported[3]')
IMG.c:45: warning: initialization makes integer from pointer without a cast
IMG.c:45: warning: excess elements in scalar initializer
IMG.c:45: warning: (near initialization for `supported[3]')
IMG.c:45: warning: excess elements in scalar initializer
IMG.c:45: warning: (near initialization for `supported[3]')
IMG.c:46: warning: braces around scalar initializer
IMG.c:46: warning: (near initialization for `supported[4]')
IMG.c:46: warning: initialization makes integer from pointer without a cast
IMG.c:46: warning: excess elements in scalar initializer
IMG.c:46: warning: (near initialization for `supported[4]')
IMG.c:46: warning: excess elements in scalar initializer
IMG.c:46: warning: (near initialization for `supported[4]')
IMG.c:47: warning: braces around scalar initializer
IMG.c:47: warning: (near initialization for `supported[5]')
IMG.c:47: warning: initialization makes integer from pointer without a cast
IMG.c:47: warning: excess elements in scalar initializer
IMG.c:47: warning: (near initialization for `supported[5]')
IMG.c:47: warning: excess elements in scalar initializer
IMG.c:47: warning: (near initialization for `supported[5]')
IMG.c:48: warning: braces around scalar initializer
IMG.c:48: warning: (near initialization for `supported[6]')
IMG.c:48: warning: initialization makes integer from pointer without a cast
IMG.c:48: warning: excess elements in scalar initializer
IMG.c:48: warning: (near initialization for `supported[6]')
IMG.c:48: warning: excess elements in scalar initializer
IMG.c:48: warning: (near initialization for `supported[6]')
IMG.c:49: warning: braces around scalar initializer
IMG.c:49: warning: (near initialization for `supported[7]')
IMG.c:49: warning: initialization makes integer from pointer without a cast
IMG.c:49: warning: excess elements in scalar initializer
IMG.c:49: warning: (near initialization for `supported[7]')
IMG.c:49: warning: excess elements in scalar initializer
IMG.c:49: warning: (near initialization for `supported[7]')
IMG.c:50: warning: braces around scalar initializer
IMG.c:50: warning: (near initialization for `supported[8]')
IMG.c:50: warning: initialization makes integer from pointer without a cast
IMG.c:50: warning: excess elements in scalar initializer
IMG.c:50: warning: (near initialization for `supported[8]')
IMG.c:50: warning: excess elements in scalar initializer
IMG.c:50: warning: (near initialization for `supported[8]')
IMG.c:51: warning: braces around scalar initializer
IMG.c:51: warning: (near initialization for `supported[9]')
IMG.c:51: warning: initialization makes integer from pointer without a cast
IMG.c:51: warning: excess elements in scalar initializer
IMG.c:51: warning: (near initialization for `supported[9]')
IMG.c:51: warning: excess elements in scalar initializer
IMG.c:51: warning: (near initialization for `supported[9]')
IMG.c:52: warning: braces around scalar initializer
IMG.c:52: warning: (near initialization for `supported[10]')
IMG.c:52: warning: initialization makes integer from pointer without a cast
IMG.c:52: warning: excess elements in scalar initializer
IMG.c:52: warning: (near initialization for `supported[10]')
IMG.c:52: warning: excess elements in scalar initializer
IMG.c:52: warning: (near initialization for `supported[10]')
IMG.c:53: warning: data definition has no type or storage class
IMG.c:55: syntax error before '*' token
IMG.c:56: warning: return type defaults to `int'
IMG.c:56: conflicting types for `IMG_Linked_Version'
include/SDL_image.h:59: previous declaration of `IMG_Linked_Version'
IMG.c: In function `IMG_Linked_Version':
IMG.c:57: syntax error before "linked_version"
IMG.c:58: `linked_version' undeclared (first use in this function)
IMG.c:58: (Each undeclared identifier is reported only once
IMG.c:58: for each function it appears in.)
IMG.c: At top level:
IMG.c:63: syntax error before '*' token
IMG.c:64: warning: return type defaults to `int'
IMG.c:64: conflicting types for `IMG_Load'
include/SDL_image.h:71: previous declaration of `IMG_Load'
IMG.c: In function `IMG_Load':
IMG.c:65: `SDL_RWops' undeclared (first use in this function)
IMG.c:65: `src' undeclared (first use in this function)
IMG.c:65: warning: implicit declaration of function `SDL_RWFromFile'
IMG.c:74: warning: return makes pointer from integer without a cast
IMG.c: At top level:
IMG.c:78: syntax error before '*' token
IMG.c:78: syntax error before '*' token
IMG.c:79: warning: return type defaults to `int'
IMG.c:79: conflicting types for `IMG_Load_RW'
include/SDL_image.h:72: previous declaration of `IMG_Load_RW'
IMG.c: In function `IMG_Load_RW':
IMG.c:80: `src' undeclared (first use in this function)
IMG.c:80: `freesrc' undeclared (first use in this function)
IMG.c:80: warning: return makes pointer from integer without a cast
IMG.c: At top level:
IMG.c:97: syntax error before '*' token
IMG.c:97: syntax error before '*' token
IMG.c:98: warning: return type defaults to `int'
IMG.c:98: conflicting types for `IMG_LoadTyped_RW'
include/SDL_image.h:69: previous declaration of `IMG_LoadTyped_RW'
IMG.c: In function `IMG_LoadTyped_RW':
IMG.c:100: `SDL_Surface' undeclared (first use in this function)
IMG.c:100: `image' undeclared (first use in this function)
IMG.c:103: `src' undeclared (first use in this function)
IMG.c:104: warning: implicit declaration of function `SDL_SetError'
IMG.c:109: warning: implicit declaration of function `SDL_RWseek'
IMG.c:111: `freesrc' undeclared (first use in this function)
IMG.c:112: warning: implicit declaration of function `SDL_RWclose'
IMG.c:117: warning: implicit declaration of function `SDL_RWtell'
IMG.c:120: request for member `is' in something not a structure or union
IMG.c:122: request for member `is' in something not a structure or union
IMG.c:127: `type' undeclared (first use in this function)
IMG.c:127: request for member `type' in something not a structure or union
IMG.c:135: request for member `load' in something not a structure or union
../Makefile.eeglobal:46: recipe for target 'IMG.o' failed
make[1]: *** [IMG.o] Error 1
make[1]: Leaving directory '/home/bat/ps2sdk-ports/sdlimage'
Makefile:101: recipe for target 'sdlimage' failed
make: *** [sdlimage] Error 2
bat@debian:~/ps2sdk-ports$ `

**Comment by BatRastard** [comment]
Yup, it was gsKit ... smooth sailing from there! Thanks again for all the help, SP193! 🥇
