### ISSUE TITLE
How do I build the ports today, in 2020?

### ISSUE THREAD

**Issue by sp193** [ps2dev/ps2sdk-ports#43]
Pardon me if it's something obvious, but how do I build any of these modules today?

Long ago, it used to be that I could just checkout a copy of ps2sdk-ports from Git and do a "make" in the projects that I want. Now, that doesn't seem to work! A lot of files are missing upon cloning the repository.
I guessed that they're now sub-modules. So I tried:
``git submodule update --init --recursive``

With this, some modules like libpng seem to become complete. However, I am still unable to compile zlib, which is a prerequisite for libpng:
```
make: *** No rule to make target 'obj/adler32.o', needed by 'lib/libz.a'.  Stop.
```

Since @AKuHAK was the last contributor to the zlib port, perhaps you could shed some light on this?

**Comment by AKuHAK** [comment]
As I know @rickgaiser changed Makefile logic. Now to build any port you should just type:
`make zlib`
If you use github folder on your pc that was downloaded before submodules were implemented, you should delete your folder and fetch the project again. Sometimes subprojects fail if there are some files inside their folders.
You can check https://github.com/ps2dev/ps2sdk-ports/blob/master/Makefile
it is also possible to make all projects by simply typing `make`.

**Comment by rickgaiser** [comment]
No, I did not make any changes to the Makefile logic:
https://github.com/ps2dev/ps2sdk-ports/commits/master/Makefile

Nor did I make any changes to the .gitmodules:
https://github.com/ps2dev/ps2sdk-ports/commits/master/.gitmodules

Git is great, but git submodules are terrible if you ask me. I also have some issues with them in combination with 'repo'.

That being said: 'make all' should work work from a freshly cloned ps2sdk-ports.

**Comment by sp193** [comment]
How strange. I hope it isn't an indicator that all the ps2sdk-ports projects must be built at once. Anyway, thank you both!
