### ISSUE TITLE
Problem linking zlib - cannot find -lkernel

### ISSUE THREAD

**Issue by yoshi314** [ps2dev/ps2sdk-ports#60]
```
/home/yoshi/opt/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/10.2.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lps2sdkc
/home/yoshi/opt/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/10.2.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lkernel
collect2: error: ld returned 1 exit status
```

I am using clean build of current git of ps2toolchain and ps2sdk, building from scratch.

**Comment by AKuHAK** [comment]
Looks like you still have links from old toolchain. Try remove all ps2 related directories before installing new toolchain.

**Comment by fjtrujy** [comment]
Hello,
I think that @AKuHAK is right. 
We just released a couple of days ago a new toolchain version. So this requires a full clean of your previous toolchain.
Anyway, the CI/CD is working fine so I can assure you that the issue that you're suffering, is a wrong configuration on your environment.

Please close the issue, whenever you double-check it.

Thanks

**Comment by yoshi314** [comment]
Could be the case, i've been using ps2toolchain repo until now. It might be missing something.

**Comment by yoshi314** [comment]
Ok it works when building everything from ps2dev repo.
